baseurl = "http://tutswiki.com/"
MetaDataFormat = "yaml"

[params]
  description = "Collaborative tutorials for the internet"
  author = "Chankey Pathak (@chankeypathak)"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Perl"
    identifier = "perl"
    pre = "<i class='fa perl'></i>"
    weight = -100
