baseurl = "http://tutswiki.com/"
MetaDataFormat = "yaml"
disableHugoGeneratorInject = true

[params]
  description = "Collaborative tutorials for the internet"
  author = "Chankey Pathak (@chankeypathak)"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Pandas Cookbook"
    identifier = "pandas"
    weight = -100
